CREATE TYPE "system_role" AS ENUM (
  'ADMIN',
  'USER'
);

CREATE TYPE "user_status" AS ENUM (
  'AVAILABLE',
  'BUSY',
  'OOO'
);

CREATE TYPE "project_status" AS ENUM (
  'PLANNING',
  'ACTIVE',
  'COMPLETED',
  'ARCHIVED'
);

CREATE TYPE "project_role" AS ENUM (
  'MANAGER',
  'MEMBER'
);

CREATE TYPE "sprint_status" AS ENUM (
  'PLANNING',
  'ACTIVE',
  'COMPLETED'
);

CREATE TYPE "task_status" AS ENUM (
  'TODO',
  'IN_PROGRESS',
  'REVIEW',
  'DONE'
);

CREATE TYPE "priority_level" AS ENUM (
  'LOW',
  'MEDIUM',
  'HIGH',
  'URGENT'
);

CREATE TYPE "chat_sender" AS ENUM (
  'USER',
  'ASSISTANT',
  'SYSTEM'
);

CREATE TYPE "notification_type" AS ENUM (
  'SYSTEM',
  'ASSIGNED',
  'DEADLINE_NEAR'
);

CREATE TYPE "heuristic_mode" AS ENUM (
  'BALANCED',
  'URGENT',
  'TRAINING'
);

CREATE TABLE "system_settings" (
  "key_name" VARCHAR PRIMARY KEY,
  "value_json" JSONB NOT NULL,
  "description" TEXT
);

CREATE TABLE "users" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "email" VARCHAR UNIQUE NOT NULL,
  "full_name" VARCHAR NOT NULL,
  "password_hash" VARCHAR NOT NULL,
  "avatar_url" TEXT,
  "role" system_role DEFAULT 'USER',
  "status" user_status DEFAULT 'AVAILABLE',
  "current_workload" INT DEFAULT 0,
  "created_at" TIMESTAMP DEFAULT (now()),
  "updated_at" TIMESTAMP DEFAULT (now())
);

CREATE TABLE "skills" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR UNIQUE NOT NULL
);

CREATE TABLE "user_skills" (
  "user_id" BIGINT,
  "skill_id" BIGINT,
  "level" INT,
  "primary" key(user_id,skill_id)
);

CREATE TABLE "projects" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" VARCHAR NOT NULL,
  "description" TEXT,
  "status" project_status DEFAULT 'ACTIVE',
  "heuristic_mode" heuristic_mode DEFAULT 'BALANCED',
  "start_date" DATE,
  "end_date" DATE,
  "created_at" TIMESTAMP DEFAULT (now())
);

CREATE TABLE "project_members" (
  "project_id" BIGINT,
  "user_id" BIGINT,
  "role" project_role DEFAULT 'MEMBER',
  "performance_score" FLOAT DEFAULT 0.5,
  "joined_at" TIMESTAMP DEFAULT (now()),
  "primary" key(project_id,user_id)
);

CREATE TABLE "sprints" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" BIGINT,
  "name" VARCHAR NOT NULL,
  "goal" TEXT,
  "status" sprint_status DEFAULT 'PLANNING',
  "heuristic_mode" heuristic_mode,
  "start_date" DATE,
  "end_date" DATE
);

CREATE TABLE "tasks" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" BIGINT,
  "parent_id" BIGINT,
  "sprint_id" BIGINT,
  "title" VARCHAR NOT NULL,
  "description" TEXT,
  "status" task_status DEFAULT 'TODO',
  "priority" priority_level DEFAULT 'MEDIUM',
  "position" FLOAT DEFAULT 0,
  "tags" "TEXT[]",
  "difficulty_level" INT DEFAULT 1,
  "required_skills" JSONB,
  "assignee_id" BIGINT,
  "reporter_id" BIGINT,
  "start_date" TIMESTAMP,
  "due_date" TIMESTAMP,
  "created_at" TIMESTAMP DEFAULT (now()),
  "updated_at" TIMESTAMP DEFAULT (now())
);

CREATE TABLE "comments" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "task_id" BIGINT,
  "user_id" BIGINT,
  "content" TEXT NOT NULL,
  "created_at" TIMESTAMP DEFAULT (now())
);

CREATE TABLE "notifications" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT,
  "title" VARCHAR NOT NULL,
  "message" TEXT,
  "type" notification_type,
  "is_read" BOOLEAN DEFAULT false,
  "link_action" VARCHAR,
  "created_at" TIMESTAMP DEFAULT (now())
);

CREATE TABLE "ai_logs" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "project_id" BIGINT,
  "user_id" BIGINT,
  "chat_message_id" BIGINT,
  "request" TEXT,
  "response" TEXT,
  "reasoning" TEXT,
  "action_taken" VARCHAR,
  "tool_output" JSONB,
  "human_feedback" VARCHAR DEFAULT 'PENDING',
  "created_at" TIMESTAMP DEFAULT (now())
);

CREATE TABLE "chat_sessions" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "user_id" BIGINT,
  "title" VARCHAR,
  "created_at" TIMESTAMP DEFAULT (now())
);

CREATE TABLE "chat_messages" (
  "id" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "session_id" BIGINT,
  "sender" chat_sender NOT NULL,
  "content" TEXT NOT NULL,
  "created_at" TIMESTAMP DEFAULT (now())
);

COMMENT ON COLUMN "system_settings"."key_name" IS 'Vd: heuristic.weights';

COMMENT ON COLUMN "system_settings"."value_json" IS 'Lưu trọng số thuật toán';

COMMENT ON COLUMN "users"."current_workload" IS 'Tổng độ khó task đang làm';

COMMENT ON COLUMN "skills"."name" IS 'Java, React, Figma';

COMMENT ON COLUMN "user_skills"."user_id" IS 'Cascade Delete';

COMMENT ON COLUMN "user_skills"."skill_id" IS 'Cascade Delete';

COMMENT ON COLUMN "user_skills"."level" IS 'Scale 1-5';

COMMENT ON COLUMN "projects"."heuristic_mode" IS 'Chế độ phân việc mặc định';

COMMENT ON COLUMN "project_members"."project_id" IS 'Cascade Delete';

COMMENT ON COLUMN "project_members"."user_id" IS 'Cascade Delete';

COMMENT ON COLUMN "project_members"."performance_score" IS 'Điểm hiệu suất P (0.0 - 1.0) của User trong dự án này';

COMMENT ON COLUMN "sprints"."project_id" IS 'Cascade Delete';

COMMENT ON COLUMN "sprints"."goal" IS 'Context cho AI';

COMMENT ON COLUMN "sprints"."heuristic_mode" IS 'Ghi đè chế độ của Project cho riêng Sprint này';

COMMENT ON COLUMN "tasks"."project_id" IS 'Cascade Delete';

COMMENT ON COLUMN "tasks"."parent_id" IS 'Subtask Logic (Cascade)';

COMMENT ON COLUMN "tasks"."sprint_id" IS 'Set Null if Sprint deleted';

COMMENT ON COLUMN "tasks"."position" IS 'Dùng để sort Kanban';

COMMENT ON COLUMN "tasks"."tags" IS 'Postgres Array: ["Bug", "Urgent"]';

COMMENT ON COLUMN "tasks"."difficulty_level" IS 'Heuristic Input (1-10)';

COMMENT ON COLUMN "tasks"."required_skills" IS 'AI Matching: ["Java", "AWS"]';

COMMENT ON COLUMN "comments"."task_id" IS 'Cascade Delete';

COMMENT ON COLUMN "ai_logs"."chat_message_id" IS 'Set NULL nếu tin nhắn gốc bị xóa';

COMMENT ON COLUMN "ai_logs"."request" IS 'Câu hỏi của User';

COMMENT ON COLUMN "ai_logs"."response" IS 'Câu trả lời của AI';

COMMENT ON COLUMN "ai_logs"."reasoning" IS 'Chain of Thought (CoT)';

COMMENT ON COLUMN "ai_logs"."action_taken" IS 'Function Calling Name';

COMMENT ON COLUMN "ai_logs"."tool_output" IS 'Kết quả trả về từ Tool/Heuristic (Vd: {"score": 9.5})';

COMMENT ON COLUMN "ai_logs"."human_feedback" IS 'PENDING, ACCEPTED, REJECTED';

COMMENT ON COLUMN "chat_messages"."session_id" IS 'Cascade Delete';

ALTER TABLE "user_skills" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "user_skills" ADD FOREIGN KEY ("skill_id") REFERENCES "skills" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "project_members" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "project_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "sprints" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tasks" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tasks" ADD FOREIGN KEY ("parent_id") REFERENCES "tasks" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tasks" ADD FOREIGN KEY ("sprint_id") REFERENCES "sprints" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tasks" ADD FOREIGN KEY ("assignee_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "tasks" ADD FOREIGN KEY ("reporter_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("task_id") REFERENCES "tasks" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "comments" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "notifications" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ai_logs" ADD FOREIGN KEY ("project_id") REFERENCES "projects" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ai_logs" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "ai_logs" ADD FOREIGN KEY ("chat_message_id") REFERENCES "chat_messages" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chat_sessions" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id") DEFERRABLE INITIALLY IMMEDIATE;

ALTER TABLE "chat_messages" ADD FOREIGN KEY ("session_id") REFERENCES "chat_sessions" ("id") DEFERRABLE INITIALLY IMMEDIATE;
